name: Run Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'
          cache: 'npm'
          
      - name: Install just
        uses: extractions/setup-just@v1
          
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
          
      - name: Install dependencies
        run: just install
      
      - name: Force install rollup optional dependency
        run: cd superchain-js && npm install @rollup/rollup-linux-x64-gnu --no-save
      
      - name: Build packages
        run: just build
      
      - name: Run tests
        run: just test
        env:
          CI: true
          NODE_ENV: test 